"""Initial migration: Create tables for weather ETL

Revision ID: 26012368b2ea
Revises: 
Create Date: 2026-03-10 09:41:47.942508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26012368b2ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ciudades_nombre', table_name='ciudades')
    op.drop_table('ciudades')
    op.drop_index('ix_metricas_etl_fecha_ejecucion', table_name='metricas_etl')
    op.drop_table('metricas_etl')
    op.drop_index('idx_ciudad_fecha', table_name='registros_clima')
    op.drop_index('ix_registros_clima_ciudad_id', table_name='registros_clima')
    op.drop_index('ix_registros_clima_fecha_extraccion', table_name='registros_clima')
    op.drop_table('registros_clima')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_clima',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ciudad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperatura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sensacion_termica', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('humedad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('velocidad_viento', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('codigo_tiempo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_extraccion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], name='registros_clima_ciudad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='registros_clima_pkey')
    )
    op.create_index('ix_registros_clima_fecha_extraccion', 'registros_clima', ['fecha_extraccion'], unique=False)
    op.create_index('ix_registros_clima_ciudad_id', 'registros_clima', ['ciudad_id'], unique=False)
    op.create_index('idx_ciudad_fecha', 'registros_clima', ['ciudad_id', 'fecha_extraccion'], unique=False)
    op.create_table('metricas_etl',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_ejecucion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('registros_extraidos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registros_guardados', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registros_fallidos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tiempo_ejecucion_segundos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metricas_etl_pkey')
    )
    op.create_index('ix_metricas_etl_fecha_ejecucion', 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.create_table('ciudades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latitud', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitud', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('activa', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ciudades_pkey')
    )
    op.create_index('ix_ciudades_nombre', 'ciudades', ['nombre'], unique=False)
    # ### end Alembic commands ###
